export enum MedicalSpecialty {
  AlergiaImunologia = "Alergia e Imunologia",
  Anestesiologia = "Anestesiologia",
  Angiologia = "Angiologia",
  Cancerologia = "Cancerologia (Oncologia)",
  Cardiologia = "Cardiologia",
  CirurgiaCardiovascular = "Cirurgia Cardiovascular",
  CirurgiaMao = "Cirurgia da Mão",
  CirurgiaCabecaPescoco = "Cirurgia de Cabeça e Pescoço",
  CirurgiaAparelhoDigestivo = "Cirurgia do Aparelho Digestivo",
  CirurgiaGeral = "Cirurgia Geral",
  CirurgiaPediatrica = "Cirurgia Pediátrica",
  CirurgiaPlastica = "Cirurgia Plástica",
  CirurgiaToracica = "Cirurgia Torácica",
  CirurgiaVascular = "Cirurgia Vascular",
  ClinicaMedica = "Clínica Médica",
  Coloproctologia = "Coloproctologia",
  Dermatologia = "Dermatologia",
  EndocrinologiaMetabologia = "Endocrinologia e Metabologia",
  Endoscopia = "Endoscopia",
  Gastroenterologia = "Gastroenterologia",
  GeneticaMedica = "Genética Médica",
  Geriatria = "Geriatria",
  GinecologiaObstetricia = "Ginecologia e Obstetrícia",
  HematologiaHemoterapia = "Hematologia e Hemoterapia",
  Homeopatia = "Homeopatia",
  Infectologia = "Infectologia",
  Mastologia = "Mastologia",
  MedicinaEmergencia = "Medicina de Emergência",
  MedicinaFamiliaComunidade = "Medicina de Família e Comunidade",
  MedicinaTrabalho = "Medicina do Trabalho",
  MedicinaTrafego = "Medicina de Tráfego",
  MedicinaEsportiva = "Medicina do Esporte",
  MedicinaFisicaReabilitacao = "Medicina Física e Reabilitação",
  MedicinaIntensiva = "Medicina Intensiva",
  MedicinaLegalPericia = "Medicina Legal e Perícia Médica",
  MedicinaNuclear = "Medicina Nuclear",
  MedicinaPreventivaSocial = "Medicina Preventiva e Social",
  Nefrologia = "Nefrologia",
  Neurocirurgia = "Neurocirurgia",
  Neurologia = "Neurologia",
  Nutrologia = "Nutrologia",
  Oftalmologia = "Oftalmologia",
  OrtopediaTraumatologia = "Ortopedia e Traumatologia",
  Otorrinolaringologia = "Otorrinolaringologia",
  Patologia = "Patologia",
  PatologiaClinica = "Patologia Clínica/Medicina Laboratorial",
  Pediatria = "Pediatria",
  Pneumologia = "Pneumologia",
  Psiquiatria = "Psiquiatria",
  Radiologia = "Radiologia e Diagnóstico por Imagem",
  Radioterapia = "Radioterapia",
  Reumatologia = "Reumatologia",
  Urologia = "Urologia",
}

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);
